### ISSUE TITLE
Unary Attributes (OPTION SELECTED)

### ISSUE THREAD

**Issue by MikeiLL** [Rosuav/choc#3]
Looking in the [docs](https://rosuav.github.io/choc/docs), I'm struggling with how to add a selected attribute to a SELECT OPTION.

```
OPTION({value: 'eager', selected: i.evaluate.to.true}, "Pick me, pick me");
```

This doesn't seem to work.

**Comment by Rosuav** [comment]
What you did there should work (assuming that the `selected` attribute does indeed evaluate to true at some point). Alternatively, you can set the `value` on the select element itself. Either should work.

**Comment by MikeiLL** [comment]
Well, assigning the value to the SELECT element worked. Will close this. Thank you!
